[package]
name = "perspective"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wassily = { path = "/Users/jeffreyrosenbluth/Rust/wassily"}
rand = "0.8.5"
image = "0.24"
rand_pcg = "0.3"